version: 2.1

orbs:
  python: circleci/python@0.2.1


jobs:
  build-and-test:
    executor: python/default
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
      - ANSIBLE_LOCAL_TEMP: /home/circleci/.ansible/tmp
      - ANSIBLE_REMOTE_TEMP: /home/circleci/.ansible/tmp
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install ansible            
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            pwd
            ~/project/venv/bin/nosetests tests
          name: Test
      - run:
          name: Execute Ansible Playbook
          command: |
            . venv/bin/activate
            whoami
            sudo ansible-playbook ansible/playbook.yml -i ansible/inventories/dev/hosts.ini
            
           
workflows:
  main:
    jobs:
      - build-and-test

    
