jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - dmz/open_tunnel:
          bastion_host: 15.207.106.156
          bastion_public_key: -----BEGIN RSA PRIVATE KEY-----
                                MIIEogIBAAKCAQEAiTTTBukkweo3QdMCPpplaAtBdrXePvMkusxhAIbsFACGQyo5
                                OZ2z21JZzFw5GBUNwIB0uSGHbrbBeA+SXZrI4k4ch9h+7I3ItMWceSS7fc0lHrWa
                                f/kOirph4Ud1zDpTSGdrUSwy7A3IaVsCJqJkrbZ2ftprSRw1XXz9+8o1iM7HnV81
                                ZIeNLHhdFaBIfNm/1Xnm4CMQTEf3Dd9K4Ue9AdseSy25aNk+sBaXCGWeJ88etljm
                                EEzr7yNzrcnTgKDr5VzYKYnmDlqtJ0dhfo1ItPKqg4iSj1Zkb/daNIpWMmmlY2k1
                                XUrwkshviP/0ebEVTzwg0V9VY4GayP+o1eKFnwIDAQABAoIBABRfXpIhHg8Y+tlw
                                Pl4TSMlZGoBI4tYP/j0qSaDtZ7JUnZrtcw/GBcWkBaddbjDQN3mE2U//1X8v7awp
                                C7+QUxGfLYdSMw5mww1sZh5qwNgeFMvphSZJUcpxgEUV+jy30FPo3ztvR6RbK43R
                                MJGR/Ub518BgKBvz70yRWZkAXlCQwoHvh/gwJA7yWJ8OlIDYytEY+P9fFdP3read
                                Gyeor4adnr+XQxKIiLBIRdeQXt9xI8UNphA2PPphJCh2iv7axxkDkkV+LpPZh8YN
                                kO6yGqM6FJa5ZiujIMuJzxnN0ly8dUes0E5fRLgbKRscPkBWe5o0AR/ML2xxD/iT
                                BDq8f1kCgYEA6P/k++aKR94z2xN57uQjc1Bxajq0yai0WOfyLQxY63KrfwAvovRX
                                Nu1sYFIfohrSLHclxL7ERGj+49OdrcXcs6ea8ajk0iJmjpUw/e5xCQiOuf3bwFkz
                                Tpy40iCAiqq7sBYKhGIbMsO9q8LFcbMUNBJ4OW8v6px5bUdeg0ME1BMCgYEAlsAm
                                Ym8s2tYVYDf/DtGiVxkmogvzGSAT2EfItnmfhbuQMCnsavXzueu7cSVJQvRxU2wf
                                SoUdf4vf7/bvQmT7rXKKEWidLwSMZe2TnSS/bS1OMBzrEWAQSkqc0+g87ss+C4Cd
                                Yg2jrU3SaHrE2nhoNqPtkQwE+hyLoFlTkhKzwcUCgYALdWI2fSz5wdS9BmUtuWyA
                                5Ejfl4mCjVhpMub3Di9lTNtgQIsXMXsEiYKV7hP+LeF+LFHgLh2K27sFS0fq3tsu
                                vqRhFBREvUpb4rxpEIvgjNowDWr8N6bNS+nO86g+qYzXaQ4VWpnJ0lSGmOqK3+qz
                                cOEWugAaQp26IRNl0yrunwKBgCbEp5ps6OYmZDzoaamP8+XeS/ckh5IQk8ntPArh
                                YEruH3ijb29abSGFJCFG635SispfZfSuIxXoDOETahhzC95hNGyhsLqkus6DuJCT
                                IL+dBRyOc012nPneElLUyMbIcd5XZyIOS+eHufKwj+t3R6W1pqTEqIsByE6maj2I
                                nb3ZAoGAdj5fm64GK1Vbrpyx8Trggnf8d4Et2WUGO2jCR1S7xsa2WEj1r3WKVeJy
                                gZlk4PbiBVe921ZiYKhHMNJctO/7j53h7/yRTXLomTQSGDBqQXTyiDOcb2IHGbec
                                4/5dwO2BALF/qrlz2TN5rmK7o0gIfSno8LxkGcZBZvJF5xqSDrk=
                                -----END RSA PRIVATE KEY-----
          bastion_user: ubuntu
          local_port: '22'
          target_host: 10.1.1.201
          target_port: '22'
      - run: 'curl localhost:22'
orbs:
  dmz: eddiewebb/dmz@volatile
version: 2.1
