
version: 2.1

orbs:
  python: circleci/python@0.2.1


jobs:
  build-and-test:
    executor: python/default
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: no
    steps:
      - add_ssh_keys:
          fingerprints:
            - "32:40:73:01:96:57:18:ae:44:9e:86:a1:eb:4d:ee:55"      
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install ansible            
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            pwd
            ~/project/venv/bin/nosetests tests
          name: Test
      - run:
          name: Execute Ansible Playbook
          command: |
            . venv/bin/activate
            whoami
            chmod 400 ~/project/CFT.pem
            tar --exclude='~/project/venv/*' -zcvf ship-passport.tar.gz *
            ansible-playbook ~/project/ansible/inventories/playbook.yml -i ~/project/ansible/inventories/dev/hosts.ini
            
           
workflows:
  main:
    jobs:
      - build-and-test
